timeout: '600s'

steps:
- id: Docker
  name: 'gcr.io/cloud-builders/docker'
  dir: patcher
  entrypoint: bash
  args: ['./build-docker.sh']

- id: Patch
  name: 'gcr.io/cloud-builders/docker'
  dir: patcher
  entrypoint: bash
  args: ['./launch-docker', './main.sh']

- id: Release
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  dir: patcher
  args: ['./release.sh']

- id: Maybe deploy
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  env:
  - 'TZ=Asia/Taipei'
  dir: web
  args: ['maybe-deploy.sh']
